### ISSUE TITLE
Specify custom domain

### ISSUE THREAD

**Issue by hongchaodeng** [h8r-dev/stacks#176]
Currently the domain `h8r.site` is hardcoded. We should let user specify it. If it is specified, we don't need to change /etc/hosts in that case.

**Comment by jack230230** [comment]
Also, there're some other preference settings need be set, such as replica size, TLS enabled, use js or ts. Shall we make a `Advanced Options` mechanism for stack?

**Comment by lyzhang1999** [comment]
`Advanced Options` is another important thing we should do, but we need to define every option for their behavior, We can open a new issue to discuss.

**Comment by jack230230** [comment]
Agree to handle the domain issue first.

**Comment by lyzhang1999** [comment]
done
