### ISSUE TITLE
[Feature] use `raw.fastgit.org` for `china_network`

### ISSUE THREAD

**Issue by hongchaodeng** [h8r-dev/stacks#238]

**Comment by lyzhang1999** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/8142348/170404526-d21b96b4-c16a-44f0-a1d2-8881ed4def32.png">
It seems this proxy can't provide SLA.

**Comment by hongchaodeng** [comment]
OK. We can't rely on this. Nor shall we recommend this to our users.
